students=[
{
name:'Navneet',
course:['JS','React','Node'],
doj:{month:'Aug',year:'2024'},
duration:4.5,
fee:12000,
mode:'Offline',
active:true
},
{
name:'Tanveen',
course:['JS','React','Node'],
doj:{month:'July',year:'2024'},
duration:5.0,
fee:13000,
mode:'Online',
active:true
},
]